### ISSUE TITLE
dotnet tool install fails to authenticate private github package registry

### ISSUE THREAD

**Issue by wildlingdev** [actions/setup-dotnet#123]
### Description
I've got a dotnet tool, published to a private github repository's package registry. I can add this source locally and it is able to install successfully, so _I think_ this problem is restricted to the github actions environment.

### Details
My workflow file contains the following two steps:

```
      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source https://nuget.pkg.github.com/WildernessLabs/index.json --name "wildernesslabs" --username WildernessLabs --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Chloroplast
        run: |
          dotnet new tool-manifest
          dotnet tool install Chloroplast.Tool --version 0.1.1 --verbosity d
```
When it gets to the `dotnet tool install`, it looks like it's unable to get the manifest for that package.
```
         Restoring packages for .NETCoreApp,Version=v3.1...
           GET https://api.nuget.org/v3-flatcontainer/chloroplast.tool/index.json
           NotFound https://api.nuget.org/v3-flatcontainer/chloroplast.tool/index.json 203ms
           GET https://nuget.pkg.github.com/WildernessLabs/download/chloroplast.tool/index.json
           NotFound https://nuget.pkg.github.com/WildernessLabs/download/chloroplast.tool/index.json 373ms
         Resolving conflicts for .NETCoreApp,Version=v3.1...
         Scanning packages for runtime.json files...
         Restoring packages for .NETCoreApp,Version=v3.1/any...
         Resolving conflicts for .NETCoreApp,Version=v3.1/any...
     1>/tmp/fd1zxmu2.vul/restore.csproj : error NU1101: Unable to find package chloroplast.tool. No packages exist with this id in source(s): nuget.org, wildernesslabs
```
**Please Note** that I'm able to run these commands and install the tool locally (using a PAT with my account, rather than `secrets.GITHUB_TOKEN`, obviously). And I'm also able to access this file directly after authenticating in the browser  
https://nuget.pkg.github.com/WildernessLabs/download/chloroplast.tool/index.json

So I'm not sure what the issue might be ... as I mentioned, because I'm able to run these commands locally, I think this is an issue with how the github actions environment, and the built in token is working, but please let me know if there's anything  I'm doing wrong in my workflow file ... thanks!
