### ISSUE TITLE
Can you bring action 'DotNetCoreCLI'?

### ISSUE THREAD

**Issue by olegburov** [actions/setup-dotnet#13]
It would be handy to have the same task as Azure DevOps does https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DotNetCoreCLIV2, where I can pass wildcard path to multiple files `.*csproj`. It's very useful when a repository has a multiple solutions with multiple projects.

For example:

```yml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
```
