### ISSUE TITLE
v1.7.0 does not set `env.DOTNET_VERSION` by default.

### ISSUE THREAD

**Issue by iris-hpaterson** [actions/setup-dotnet#130]
### Description

The new release of `setup-dotnet`, v1.7.0, does not set the `DOTNET_ROOT` environment variable. Previous versions did set this variable by default.

Other Dotnet related actions, such as Microsoft Azure's `webapps-deploy` and the CI files they provide by default, depend on the `DOTNET_ROOT` variable being set, and are broken by this release.

### Details

Dotnet 3.1.x

[Azure webapp-deploy](https://github.com/Azure/webapps-deploy) depends on the `DOTNET_ROOT` variable being set, as do Azure's provided CI files:

```
with:
        app-name: 'XXX`
        slot-name: 'XXX'
        publish-profile: ${{ secrets.XXX }}
        package: ${{ env.DOTNET_ROOT }}/myapp
```

I mentioned this in passing in #128, but #128 is about the `v3.1.x` versions no longer working, so I'm filing this as a separate issue.

Update: Azure webapp-deploy dosn't depend on `DOTNET_ROOT` in it's core action code, but the CI files Azure provides when setting up Azure webapp deployment for .NET, using Github as the build server, uses the variable during the publish and deploy phase to indicate paths to the app. 

Example of a broken CI file provided by Azure:

```yml
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - XXX

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'  # This also breaks. See #128 in 'setup-dotnet'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp   # This breaks because DOTNET_ROOT is empty.

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'XXX'
        slot-name: 'XXX'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_XXX }}
        package: ${{env.DOTNET_ROOT}}/myapp     # This also breaks, if the `dotnet publish is hardcodded.
```
