### ISSUE TITLE
dotnet dev-certs started failing in macOS

### ISSUE THREAD

**Issue by kblok** [actions/setup-dotnet#134]
**Description**  
The `dotnet dev-certs` started to fail here https://github.com/hardkoded/playwright-sharp/pull/878/checks?check_run_id=1176770064 from one day to the other.

This is part of the workflow definition.

```
jobs:
  chromium-mac:
    name: Chromium on MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Create Certificate
        run: |
          dotnet dev-certs https --clean
          dotnet dev-certs https -ep src/PlaywrightSharp.TestServer/testCert.cer
````

You can see the rest here https://github.com/hardkoded/playwright-sharp/blob/master/.github/workflows/tests.yml

Coming from https://github.com/actions/virtual-environments/issues/1690

**Comment by ZEisinger** [comment]
Likely related: https://github.com/dotnet/aspnetcore/issues/19590

The new updates made the default to use the same install path as virtual-environments so we don't reinstall dotnet everytime, but this might cause it to use a newer `dotnet.exe` version. It seems like you were using the last known good version with 3.1.100 (regression began in 3.1.102). Setting a distinct install directory should force using the 3.1.100 version of dotnet.exe you were using previously.
``` yaml
     - uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 3.1.100
       env:
         DOTNET_INSTALL_DIR: ~/alternate/dotnet
```

It needs more investigation, but we need to check for certificates on macos virtual-environments that could cause this particular failure for 3.1.x.
