### ISSUE TITLE
Unable to test using older target frameworks following setup

### ISSUE THREAD

**Issue by JimBobSquarePants** [actions/setup-dotnet#136]
### Description

Running dotnet test following setup does not allow testing against specific older frameworks. This used to be possible.

### Details

Given the following workflow.

``` yml
name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
        matrix:
            options:
                - os: windows-latest
                  framework: netcoreapp3.1
                - os: windows-latest
                  framework: netcoreapp2.1

    runs-on: ${{matrix.options.os}}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore -f ${{matrix.options.framework}}

    - name: Test
      run: dotnet test --no-restore --verbosity normal -f ${{matrix.options.framework}}

```

It used to be possible to specify an older target framework. For example : 

```
dotnet test --no-restore --verbosity normal -f netcoreapp2.1
```

Now the following exception is returned instead.

```
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.9 at [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64
. Please check the diagnostic logs for more information.
```

Build works fine and removing this action allows the test command to run as expected.

I've created a repository that demonstrates the issue.
https://github.com/JimBobSquarePants/SetupDotNetActionFailRepro
