### ISSUE TITLE
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.

### ISSUE THREAD

**Issue by litetex** [actions/setup-dotnet#137]
### Description

When running setup-dotnet the following warning appears:
```
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
```

Is this a problem?

### Details

```YAML
name: Develop CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
```

complete action output:
```
Run actions/setup-dotnet@v1
/home/runner/work/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh --version 3.1.403
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.403/dotnet-sdk-3.1.403-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.403/dotnet-sdk-3.1.403-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/runner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
/home/runner/.dotnet:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
https://github.com/litetex/TopGHRepos/runs/1276675989
