### ISSUE TITLE
Update Documentation To Reference Latest Version

### ISSUE THREAD

**Issue by aolszowka** [actions/setup-dotnet#139]
### Description
The documentation in README.md should be updated to reflect the latest/greatest version of the Action.

### Details
I was having issues using the provided example to push a package to GPR, however after reading https://github.com/actions/setup-dotnet/issues/101#issuecomment-686656113 it appears it was because I was using an older release (`@v1` as opposed to `@v1.7.2`)

Out of the box (and not knowing any better) I simply copy and pasted the example to get started.

This would improve on boarding for new users.

**Comment by GGG-KILLER** [comment]
The `v1` tag is pointing to the same version as the `v1.7.2` tag:
![image](https://user-images.githubusercontent.com/5892127/98386044-7d6fde80-202e-11eb-9fd0-e291751b2f38.png)

**Comment by aolszowka** [comment]
Interesting, didn't work for me until I explicitly changed the version, if that is what is expected more power to ya.

**Comment by vsafonkin** [comment]
Hello @aolszowka , do you still have any issues with it?

**Comment by aolszowka** [comment]
@vsafonkin In my usages I needed to explicitly declare the tag.

However the only reason I was using this was to push to the GitHub Package Repo (GPR) however this even became flaky itself, so I have switched to explicitly declaring the repo and not relying on this setup action like so:

```yaml
      # Publish the Package, but only if on Master
      - name: Publish the package to GPR (Release ONLY)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: dotnet nuget push 'nupkg/*.nupkg' --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

As this has not received any traction I am just going to close this as "wont-fix".
