### ISSUE TITLE
Question/feature - method to request 'latest pre-installed version'

### ISSUE THREAD

**Issue by ericsampson** [actions/setup-dotnet#140]
Hi, with the version format `3.1.x`, is there a way to tell it to limit itself to the versions pre-installed on the runner?

Thanks!

**Comment by vsafonkin** [comment]
Hi @ericsampson, you can just don't use the setup task. In this case the latest pre-installed version will be used in your project.

**Comment by ericsampson** [comment]
@vsafonkin from what I've read in people's blogs online, and seen at my own company, I don't think people understand this (maybe it's not clear from the docs?) because I see `setup-dotnet` used all over, when it doesn't have to be.

So it would be nice to have something like I mentioned as a no-op, to save time pulling down versions that are already installed. 

The other reason we use this action is to set up NuGet credentials for private NuGet servers, in which case to would also be nice to use the action without pulling down a preinatalled version

**Comment by vsafonkin** [comment]
@ericsampson , you can use action without specifying version, only set up NuGet credentials:
```
- name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        source-url: <url>
      env:
        NUGET_AUTH_TOKEN: <token_variable>
```
In this case it will be uses the latest pre-installed version (or version from global.json file, if you created this file) and nuget.config will be generated.
