### ISSUE TITLE
Support multiple versions in a single invocation

### ISSUE THREAD

**Issue by adamralph** [actions/setup-dotnet#146]
I know I can do this:

```yaml
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '2.1.811'
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '3.1.404'
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '5.0.100'
```

but I'd like to do this:

```yaml
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-versions: ['2.1.811', '3.1.404', '5.0.100']
```
