### ISSUE TITLE
macos-latest using .NET 5 even when 3.1.404 is installed.

### ISSUE THREAD

**Issue by jsm174** [actions/setup-dotnet#157]
### Description

We are building a netcoreapp3.1 app for `win-x64`, `win-x86`, `osx-x64`, `linux-x64`.

With the transition to .NET 5 recently, we started using this action to install .NET 3.1.x.

```
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: nuget/setup-nuget@v1
      - name: Build
        run: dotnet build -c Release -r win-x64
.
.
.
      - name: Build
        run: dotnet build -c Release -r osx-x64
```

In our action, we started receiving errors with `macos-latest`. (I realize they have been undergoing maintenance).

### Details

Even though with the 3.1.x installed, `macos-latest` still tries to use .NET 5.

```
Run actions/setup-dotnet@v1
  with:
    dotnet-version: 3.1.x
/Users/runner/work/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh --version 3.1.404
dotnet-install: .NET Core SDK version 3.1.404 is already installed.
dotnet-install: Adding to current process PATH: `/Users/runner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
.
.
.
Run dotnet build -c Release -r osx-x64
  dotnet build -c Release -r osx-x64
  shell: /bin/bash -e {0}
  env:
    DOTNET_ROOT: /Users/runner/.dotnet
    NUGET: /Users/runner/hostedtoolcache/nuget.exe/5.8.0/x64/nuget.exe
##[debug]/bin/bash -e /Users/runner/work/_temp/20349d6d-af1b-4a00-91bf-dac4a4052cf2.sh

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.101
.
.
.
Error: /Users/runner/.dotnet/sdk/5.0.101/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(27,5): error NETSDK1134: Building a solution with a specific RuntimeIdentifier is not supported. If you would like to publish for a single RID, specifiy the RID at the individual project level instead. [/Users/runner/work/VisualPinball.Engine/VisualPinball.Engine/VisualPinball.Engine.sln]

Build FAILED.
```

All the other builders are working fine, for example `linux-x64`:

```
Run actions/setup-dotnet@v1
  with:
    dotnet-version: 3.1.x
/home/runner/work/_actions/actions/setup-dotnet/v1/externals/install-dotnet.sh --version 3.1.404
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.404/dotnet-sdk-3.1.404-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.404/dotnet-sdk-3.1.404-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/runner/.dotnet`. Note: This change will be visible only when sourcing script.
.
.
.
Run dotnet build -c Release -r linux-x64
  dotnet build -c Release -r linux-x64
  shell: /bin/bash -e {0}
  env:
    DOTNET_ROOT: /home/runner/.dotnet
    NUGET: /opt/hostedtoolcache/nuget.exe/5.8.0/x64/nuget.exe
##[debug]/bin/bash -e /home/runner/work/_temp/3f736cb0-8f50-4b74-ac69-d188f9015140.sh

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.404
```

**Comment by jsm174** [comment]
Just wanted to give an update on this.

For the time being, I added a step that generates a `global.json` that forces `3.1.x`.

```
  build-osx-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: nuget/setup-nuget@v1
      - name: Force 3.1.x
        run: |
          echo "{ \"sdk\": { \"version\": \"3.1.0\", \"rollForward\": \"latestFeature\" } }" > global.json
      - name: Build
        run: dotnet build -c Release -r osx-x64
      - name: Build Contents
        run: ls -lart VisualPinball.Engine.Test/.bin/Release/netcoreapp3.1
      - name: Test
        run: dotnet test -r osx-x64
```
