### ISSUE TITLE
Unable to use .Net 6.0 preview

### ISSUE THREAD

**Issue by afucher** [actions/setup-dotnet#170]
**Description:**
I'm trying to update my project with the preview version of .NET 6, but when I try to set the version on `setup-dotnet` to 6 it doesn't find the version to download.

**Task version:**
`actions/setup-dotnet@v1`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
My repo is private, but to reproduce just need to set the version to `6.0.0` or `6.0.0-preview.1`

**Expected behavior:**
It should download the sdk and setup all the env.

**Actual behavior:**
It doesn't find the preview, and show this error:
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.0-preview/dotnet-sdk-6.0.0-preview-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.0-preview/dotnet-sdk-6.0.0-preview-linux-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.0-preview/dotnet-dev-ubuntu.18.04-x64.6.0.0-preview.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.0-preview/dotnet-dev-ubuntu.18.04-x64.6.0.0-preview.tar.gz
dotnet_install: Error: Could not find/download: `.NET Core SDK` with version = 6.0.0-preview
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```

**Comment by blai30** [comment]
Specify the `dotnet-version` to be `6.0.100-preview.1.21103.13`. This worked for me.

**Comment by AraHaan** [comment]
Yep, I normally always even on stable do the exact version from the release metadata.

**Comment by LanceMcCarthy** [comment]
For preview3, this following works for me

```
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '6.0.100-preview.3.21202.5'
```

**Comment by GGG-KILLER** [comment]
v1.8.0 has been released which includes #110.
Should resolve this by simply doing:
```yml
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0
        include-prerelease: True
```
