### ISSUE TITLE
5.x does not work

### ISSUE THREAD

**Issue by njlr** [actions/setup-dotnet#173]
**Description:**

Cannot specify .NET version `5.x`

**Task version:**
`master` and `v1.7.2`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

```
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.x
```

**Actual behavior:**
Fails
