### ISSUE TITLE
Pre-installed .NET SDK binaries are ignored and re-installed

### ISSUE THREAD

**Issue by MichaelGrafnetter** [actions/setup-dotnet#179]
**Description:**
The `setup-dotnet` action always downloads the .NET SDK to `windows-latest` hosted VM, even if the requested version of .NET SDK is already [pre-installed](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) on the machine in `C:\Program Files\dotnet\sdk` . This behavior unnecessarily prolongs the job execution:

![image](https://user-images.githubusercontent.com/8986376/113272610-17853b80-92dc-11eb-8abd-1a50ffebc0b0.png)

Or am I missing a parameter/variable that changes this default behavior?

**Task version:**
`actions/setup-dotnet@v1`

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**
build.yml excerpt:
```yml
jobs:
  build:
    name: 'Build'
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core 2
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '2.1.x'
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '5.0.x'
```

**Expected behavior:**
Locate the pre-installed .NET SDK 5.0.201 in `C:\Program Files\dotnet\sdk` and just add it to PATH. Optionally create a symlink pointing to the appropriate SDK directory from `C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\`.

**Actual behavior:**
According to the following log from GitHub Actions, `dotnet-sdk-5.0.201-win-x64.zip` is downloaded and extracted during the installation process:
```txt
Run actions/setup-dotnet@v1
  with:
    dotnet-version: 5.0.x
  env:
    DOTNET_NOLOGO: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_actions\actions\setup-dotnet\v1\externals\install-dotnet.ps1' -Version 5.0.201"
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201/dotnet-sdk-5.0.201-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.201/dotnet-sdk-5.0.201-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
C:\Users\runneradmin\AppData\Local\Microsoft\dotnet;C:\Users\runneradmin\AppData\Local\Microsoft\dotnet;C:\Users\runneradmin\.dotnet\tools;...
```

**Comment by GGG-KILLER** [comment]
I'd like to add that this is also an issue on Linux (it's only not an issue on macOS).

**Comment by vsafonkin** [comment]
Hi @MichaelGrafnetter, the reasons of this behavior are described here: https://github.com/actions/setup-dotnet/blob/64df20e5ef65c9dbbea8418a698af6902f1fbcb7/docs/adrs/v2-setup-dotnet.md

You can use `DOTNET_INSTALL_DIR` environment variable to fix it in runtime:
```
- name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
        env:
          DOTNET_INSTALL_DIR: 'C:\Program Files\dotnet'
```
