### ISSUE TITLE
example for dotnet 3.0 builds

### ISSUE THREAD

**Issue by ctaggart** [actions/setup-dotnet#18]
It may be worth changing the matrix example in the readme to be `3.0.100-preview8-013656` as an example for the https://dotnet.microsoft.com/download/dotnet-core/3.0 sdks.

It is great that this works and fast!
``` yaml
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview8-013656
```

https://github.com/ctaggart/froto/runs/195450477
