### ISSUE TITLE
Comprehensive example

### ISSUE THREAD

**Issue by cilerler** [actions/setup-dotnet#19]
The actual example doesn't help much to cover a real-life scenario. It would be beneficial if you may give us a complete example that includes the steps below.

1. build with a version number _(requires grabbing `$(BuildId)`)_
2. run the test
3. tag the source upon successful build & test
4. deploy the artifacts to GitHub releases and GitHub packages

I understand that 3rd and 4th are not the concepts of this repository. However, it will give us a jump start with GitHub Actions.  Without those above, it is challenging to play with it unless we create our environment with Docker, which will defeat the purpose of this repository.

Here is the initial draft where I stuck.

## GitHub Actions version

```yaml
name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run: dotnet build ./src/MyProject/MyProject.csproj --configuration Release /p:BuildNumber=1.0.820
    - name: Publish
      run: dotnet publish ./src/MyProject/MyProject.csproj --configuration Release
    - name: Pack
      run: dotnet pack ./src/MyProject/MyProject.csproj --no-build /p:Configuration=release /p:PackageVersion=1.0.820 --verbosity Detailed
```

### Variables on VSTS

```text
Parameters.RestoreBuildProjects = **/MyProject.csproj
Parameters.TestProjects = **/*Tests/MyProject.Tests.csproj
BuildConfiguration = Release
Build.BuildNumber = $(MajorVersion).$(MinorVersion).$(BuildId)
build.artifactstagingdirectory = 
```

### Commands on VSTS

```yaml
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) /p:BuildNumber=$(Build.BuildNumber)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration) /p:BuildNumber=$(Build.BuildNumber)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: '$(Parameters.RestoreBuildProjects)'
    nobuild: true
    versioningScheme: byBuildNumber

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
```
