### ISSUE TITLE
API key is ignored

### ISSUE THREAD

**Issue by robertvazan** [actions/setup-dotnet#190]
**Description:**
The problem described in #66 is still there.

**Task version:**
v1

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Repro steps:**  
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
    - name: Build
      run: dotnet pack --configuration Release
    - name: NuGet push
      run: dotnet nuget push */bin/Release/*.nupkg
```

**Expected behavior:**
Per README, this should push the package to nuget repository.

**Actual behavior:**
```
warn : No API Key was provided and no API Key could be found for 'https://www.nuget.org/api/v2/package'. To save an API Key for a source use the 'setApiKey' command.
...
error: Response status code does not indicate success: 401 (An API key must be provided in the 'X-NuGet-ApiKey' header to use this service).
```

**Workaround:**
I could only make nuget push work by providing API key and source URL on command line.

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet pack --configuration Release
    - name: NuGet push
      run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
```

If this issue cannot be fixed, then it would be best to modify examples in README to use the above workaround.
