### ISSUE TITLE
If Working-directory is set, got errors with GPR

### ISSUE THREAD

**Issue by brunohbrito** [actions/setup-dotnet#193]
**Description:**
When I set `defaults.run.working-directory` and I try to run `dotnet nuget push` to Github Nuget Package. It returns <del>403</del>401.
It's really weird and doesn't make sense at first glance. But I figure out the bug after 8 hours digging into it.

**Task version:**
actions/setup-dotnet@v1

**Platform:**
- [ X] Ubuntu

**Runner type:**
- [ X] Hosted

**Repro steps:**  
I've these simple steps:

```yaml
  package:
    runs-on: ubuntu-latest
    name: Update NuGet package
    needs: build
    defaults:
      run:
        working-directory: ./src

    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/OWNER/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        

      - name: Generate Package
        run: dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true
```
![image](https://user-images.githubusercontent.com/7241156/116769493-fc106c00-aa12-11eb-984f-c74ae57d8c30.png)

If I remove `defaults.run.working-directory` and change `dotnet pack ./src -c Release -o out` It magically get pushed.
![image](https://user-images.githubusercontent.com/7241156/116769519-311cbe80-aa13-11eb-8858-93e0127da79e.png)

**Expected behavior:**
nuget package pushed

**Actual behavior:**
Error <del>403</del>401.
