### ISSUE TITLE
.NET 6.0 RC-1 does not work in Github Action

### ISSUE THREAD

**Issue by ThomasBleijendaal** [actions/setup-dotnet#232]
**Description:**
I've tried to use the new .NET 6.0 RC-1 in a github action, but that failed to run.

**Task version:**
v1

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Please check https://github.com/ThomasBleijendaal/durable-dice/runs/3667892988?check_suite_focus=true. 

I used this in my build pipeline definition
```yml
- name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
```

**Expected behavior:**
Builds with the new .NET 6.0 RC-1 should work. 

**Actual behavior:**
Errors and after reverting to 6.0.100-preview.7.21379.14 the pipeline worked again.
