### ISSUE TITLE
Why can't I automatically publish to GitHub packages?

### ISSUE THREAD

**Issue by bbhxwl** [actions/setup-dotnet#235]
error 

Run dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
Pushing AdlCommon.1.0.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 492ms
error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).

```
name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/bbhxwl/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.TOKEN}}
    - run: dotnet build AdlCommon
    - name: Create the package
      run: dotnet pack --configuration Release AdlCommon
    - name: Publish the package to GPR
      run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.TOKEN }}
```
