### ISSUE TITLE
,NET 6 RC2 version support

### ISSUE THREAD

**Issue by sowsan** [actions/setup-dotnet#242]
Setup .NET RC2 / latest versions..

I am trying to setup DOTNET_CORE_VERSION: 6.0.0-rc.2.21480.5 with  include-prerelease: True

It keeps failing with the error below... so far only working one is DOTNET_CORE_VERSION: 6.0.100-rc.1.21458.32. Any idea how to get the support for latest version of .NET 6?

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.0-rc.2.21480.5/dotnet-sdk-6.0.0-rc.2.21480.5-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.0-rc.2.21480.5/dotnet-sdk-6.0.0-rc.2.21480.5-linux-x64.tar.gz is not available.
dotnet_install: Error: Could not find `.NET Core SDK` with version = 6.0.0-rc.2.21480.5
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
Error: The process '/home/runner/work/_actions/actions/setup-dotnet/v1.8.0/externals/install-dotnet.sh' failed with exit code 1

**Comment by vsafonkin** [comment]
Hi @sowsan, looks like you specified `runtime` version, not `sdk`: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json

You can use this step to install the latest sdk and runtime:
```
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true
```
Test run: https://github.com/vsafonkin/dotnet-setup-test/runs/4064878009?check_suite_focus=true

**Comment by toklive** [comment]
Thanks for the clarification @vsafonkin  :) , that worked !!!

**Comment by ralftar** [comment]
What about support for 6.0.100 (RTM, not RC)? Does one have to state version explicit with `dotnet-version: '6.0'` or will it become implicit as with earlier versions?

**Comment by ralftar** [comment]
What about support for 6.0.100 (RTM, not RC)? Does one have to state version explicit with `dotnet-version: '6.0'` or will it become implicit as with earlier versions?

**Comment by vsafonkin** [comment]
@ralftar, you can install .NET 6.0.100 without `include-prereleaase` option at the moment:
 ```
- name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
```
It will be install the latest stable version from `6.0` channel: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json
