### ISSUE TITLE
It is impossible to use Matrix Testing with different frameworks

### ISSUE THREAD

**Issue by KungA** [actions/setup-dotnet#247]
I have to test multitargeted library with frameworks matrix, but it is impossible to map target framework to dotnet-version.

For example, I have workflow:

```
strategy:
  fail-fast: false
  matrix:
    framework: [net48, netcoreapp2.1, netcoreapp3.1, net5.0, net6.0]

steps:
- name: Install .NET
  uses: actions/setup-dotnet@main
  with:
    dotnet-version: ???
  
- name: Test
  run: dotnet test <my project> --framework ${{ matrix.framework }}
```

and want to install only `dotnet 2.1.x` for `netcoreapp2.1` target,  `dotnet 5.0.x` for `net5.0` target  and so on.

Also, it seems that installing only dotnet 6.0.x [is not enough](https://github.com/vostok/applications.aspnetcore/actions/runs/1476861692) to run tests under net5.0.

**Comment by vsafonkin** [comment]
Hi @KungA, looks like you have to use setup task multiple times with if condition. For example:
```
strategy:
  fail-fast: false
  matrix:
    framework: [ netcoreapp3.1, net5.0, net6.0 ]

steps:
- name: Install .NET 3.1
  if: ${{ matrix.framework == 'netcoreapp3.1' }}
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 3.1.x

- name: Install .NET 5.0
  if: ${{ matrix.framework == 'net5.0' }}
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 5.0.x

- name: Install .NET 6.0
  if: ${{ matrix.framework == 'net6.0' }}
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 6.0.x
  
- name: Test
  run: dotnet test <my project> --framework ${{ matrix.framework }}
```

**Comment by KungA** [comment]
Yeah, but it is very huge and inconvinient constructions :)
For now, I will wait #240 and install all tools every time.

**Comment by kzrnm** [comment]
I don't think it's necessary to specify a target.

```xml
<TargetFrameworks>net48;netcoreapp2.1;netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
```

```yml
steps:
- name: Install .NET 2.1
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 2.1.x

- name: Install .NET 3.1
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 3.1.x

- name: Install .NET 5.0
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 5.0.x

- name: Install .NET 6.0
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 6.0.x
  
- name: Test
  run: dotnet test <my project>  # Running multiple test targets
```

**Comment by KungA** [comment]
Without target specification and matrix our tests will be running 5x times longer (3 vs 15 minutes in my case).

Also, it is much easier to find falling framework & platform combination if test them separately.

<img width="216" alt="Screen Shot 2021-11-21 at 13 28 17" src="https://user-images.githubusercontent.com/6822967/142755125-4b8ca386-faa6-4467-a845-f4afdd86c392.png">

**Comment by kzrnm** [comment]
Since you are targeting 5 frameworks, I think it is natural that your tests take 5x times longer.

**Comment by KungA** [comment]
What do you think about introducing a new parameter for frameworks passing?

```
steps:
- name: Install .NET
  uses: actions/setup-dotnet@v1
  with:
    dotnet-framework: [ netcoreapp3.1, net5.0, net6.0 ]
```

With it `setup-dotnet` should just easily map them to the corresponding dotnet-version.
