### ISSUE TITLE
.NET Standard 2.0

### ISSUE THREAD

**Issue by jwillmer** [actions/setup-dotnet#266]
I'm a little bit lost. I try to maximize the usability of my library by compiling it for .NET Standard 2.0 but I don't know how I need to configure this action in order to do so. Is there some example?

**Comment by vsafonkin** [comment]
Hi @jwillmer, I believe you can use .NET 5.0 because it compatible with netstandart 2.0: [link](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#when-to-target-net50-or-net60-vs-netstandard)
```yaml
- name: Setup dotnet
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 5.0.x
```
