### ISSUE TITLE
nuget restore missing packages 

### ISSUE THREAD

**Issue by clmcgrath** [actions/setup-dotnet#27]
Not really sure where to put this , 
this i think applies more to the windows base image than to setup-dotnet 
but i can't find anywhere to post issues for the base images or the agents in general 

nuget restore is missing packages 
i am using the action file below 
when i run nuget restore locally i get 15 packages restored
but when it is runs on github it only restores 1 package ,  json.net  and causes the build to fail 

```
name: Build Points Calculator

on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup VSWhere.exe
      uses: warrenbuckley/Setup-VSWhere@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Restore 
      run: nuget restore .\AwardScenePoints.sln

    - name: Build Solution 
      run: powershell -Command " $msbuild = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe;  & "$msbuild" AwardScenePoints.sln "
```
