### ISSUE TITLE
OCI oracle cloud github runner failed

### ISSUE THREAD

**Issue by ozkanpakdil** [actions/setup-dotnet#295]
**Description:**
When I ran setupdotnet with oracle cloud arm64. I got the error below

**Task version:**
2

**Platform:**
- [x] Oracle linux

**Runner type:**
- [x] Self-hosted

**Repro steps:**  
https://github.com/ozkanpakdil/test-microservice-frameworks/ and here is runner log https://github.com/ozkanpakdil/test-microservice-frameworks/runs/6378838725?check_suite_focus=true

**Actual behavior:**
/actions-runner/_work/_actions/actions/setup-dotnet/v2/externals/install-dotnet.sh: line 781: HOME: unbound variable
mkdir: cannot create directory ‘’: No such file or directory
Error: The process '/actions-runner/_work/_actions/actions/setup-dotnet/v2/externals/install-dotnet.sh' failed with exit code 1

is there a workaround like defining /tmp as HOME ? or what is the proper way ?

Thanks

**Comment by vsafonkin** [comment]
Hi @ozkanpakdil, we will take a look at this, thank you for your report.

**Comment by ozkanpakdil** [comment]
do you need anything tested feel free to contact me. I like to see this working :)

**Comment by vsafonkin** [comment]
@ozkanpakdil, could you try to set `DOTNET_INSTALL_DIR` environment variable? You can use any directory on your self-hosted machine for it.

```yaml
- name: Setup dotnet
  uses: actions/setup-dotnet@v2
  with:
    dotnet-version: '6.0.x'
  env:
    DOTNET_INSTALL_DIR: 'directory for .NET installation'
```
