### ISSUE TITLE
nuget/push/github - --skip-duplicate flag is still being ignored

### ISSUE THREAD

**Issue by PieterjanDeClippel** [actions/setup-dotnet#299]
**Description:**
I have a [git repository](https://github.com/MintPlayer/MintPlayer.AspNetCore.Templates) with a .NET solution containing .NET Core templates. There's a workflow set up to build/publish a nuget package to **nuget.org** and my **github feed**.

```
name: publish-master

on:
  push:
    branches: [ master ]

jobs:
  build:

    name: publish-master
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.100
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
    
    #- name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1.1
    
    - name: Install dependencies
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
        
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release
      
    - name: PushNuget
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TO_NUGET_ORG }} --skip-duplicate
      
    - name: PushGithub
      # run: nuget.exe push "**/*.nupkg" -NoSymbols -SkipDuplicate
      run: dotnet nuget push "**/*.nupkg" --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
```

The workflow still fails when the package version already exists at the github.com feed, even though the `--skip-duplicate` flag was specified:

    dotnet nuget push "**/*.nupkg" --no-symbols --skip-duplicate

The corresponding `msbuild` command on the other hand works fine:

    nuget.exe push "**/*.nupkg" -NoSymbols -SkipDuplicate

**Task version:**

    actions/setup-dotnet@v2.1.0

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
The workflow with repository is hosted [here](https://github.com/MintPlayer/MintPlayer.AspNetCore.Templates/blob/master/.github/workflows/publish-master.yml)

**Expected behavior:**
The workflow step should succeed when the `--skip-duplicate` flag is specified, and the package already exists at the github.com feed.

**Actual behavior:**
- The workflow fails
- The workflow does NOT fail for the nuget.org global feed

**Discussions**
- [The response ended prematurely.An error occurred while sending the request](https://github.community/t/push-nuget-package-to-github-com-the-response-ended-prematurely-an-error-occurred-while-sending-the-request/131032/2) (Was because the package size was too large)
- [GitHub Actions: automatically push NuGet package](https://github.community/t/github-actions-automatically-push-nuget-package/128242/13)
