### ISSUE TITLE
How to use dotnet 7.0.*

### ISSUE THREAD

**Issue by SpringHgui** [actions/setup-dotnet#300]
How to use dotnet 7.0.*

**Comment by e-korolevskii** [comment]
Hello @SpringHgui,
To use prerelease versions you can add `include-prerelease: true` flag. 
```
- uses: actions/setup-dotnet@v2
  with:
    dotnet-version: '7.0.x'
    include-prerelease: true
```
More about this you can see in the [documentation](https://github.com/actions/setup-dotnet/blob/main/action.yml).
