### ISSUE TITLE
Could not find dotnet core version (.Net 7)

### ISSUE THREAD

**Issue by menfra** [actions/setup-dotnet#323]
**Description:**
I have a script which uses: actions/setup-dotnet@v2.1.0  with dotnet-version: 7.0.x

However I keep getting the Error: Could not find dotnet core version. Please ensure that the specified version 7.0.x is valid.

Is there a specific version of the action that works for .NET 7?

**Comment by IvanZosimov** [comment]
Hi, @menfra 👋 Thanks for the question. As the .NET 7.0 is still in the prerelease phase - the latest version is "7.0.100-rc.1.22431.12", you need to specify input `include-prerelease`: 
```yaml 
- uses: actions/setup-dotnet@v2
  with:
        dotnet-version: 7.0.x
        include-prerelease: true
```
I'm going to close this issue, If you have any additional questions feel free to ping us.
