### ISSUE TITLE
Publish to NuGet error: Please specify the path to the package.

### ISSUE THREAD

**Issue by miroiu** [actions/setup-dotnet#330]
**Description:**
Unable to publish NuGet package using the command line.

![image](https://user-images.githubusercontent.com/12727904/194155643-0e600b3c-cd48-41da-b2bf-c3511784c530.png)

**Task version:**
3.0.1

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
Workflow file: https://github.com/miroiu/nodify/actions/runs/3192383906/workflow

```yaml
name: Publish package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish the package
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k $NUGET_AUTH_TOKEN */bin/Release/*.nupkg
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
      
```

**Expected behavior:**
NuGet package is published.

**Actual behavior:**
Action fails with error saying that it cannot find the path to the package.
