### ISSUE TITLE
Error with dotnet ef migrations bundle when using v3

### ISSUE THREAD

**Issue by mabster** [actions/setup-dotnet#341]
**Description:**
We upgraded our GitHub workflow from setup-dotnet@v1 to setup-dotnet@v3 and started seeing an error in the "dotnet ef migrations bundle" command, as detailed in the GitHub issue I raised against the efcore repo:

https://github.com/dotnet/efcore/issues/29491

Downgrading to setup-dotnet@v2 resolves the issue.

**Task version:**
v3

**Platform:**
- [x] Windows

**Runner type:**
- [x] Hosted

**Repro steps:**  
```
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Install EF Tool
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef

... build and publish solution ...

      - name: Generate EF migration script
        run: dotnet ef migrations bundle --startup-project Puckster.Server --output ./efbundle.exe --configuration Bundle --verbose
```

**Expected behavior:**
efbundle.exe is generated successfully.

**Actual behavior:**
```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.10\Sdk\WasmApp.targets(161,5): error : $(MicrosoftNetCoreAppRuntimePackDir)='', and cannot find %(ResolvedRuntimePack.PackageDirectory)=. One of these need to be set to a valid path [D:\a\puckster\puckster\Puckster.Client\Puckster.Client.csproj]
```
