### ISSUE TITLE
Run auth util but skip dotnet installation

### ISSUE THREAD

**Issue by sliekens** [actions/setup-dotnet#345]
**Description:**
I would like to be able to run the auth util only and skip the dotnet installer.

``` yml
- name: Configure GPR authentication
  uses: actions/setup-dotnet@v3
  env:
    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  with:
    source-url: https://nuget.pkg.github.com/sliekens/index.json
    dotnet-version: 'none'
    global-json-file: 'ignore ./global.json'
```

**Justification:**
  I'm running [jobs inside a container](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container) that already contains the exact SDK versions needed.
  
**Are you willing to submit a PR?**

It depends
