### ISSUE TITLE
Matrix example in README doesn't work in v3

### ISSUE THREAD

**Issue by erikdesj** [actions/setup-dotnet#351]
**Description:**
The readme has an example that _looks_ like it runs a build using .NET Core 2.1, 3.2, and 5. It actually runs all three matrix builds using .NET 7, because it happens to be installed.

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build <my project>
```

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
See the workflow defined in https://github.com/erikdesj/setup-dotnet-test/blob/main/.github/workflows/ci.yml. It is almost exactly the same as the readme, but it just logs the .NET version.

When running each job, they don't end up using the specified .NET version, but instead all use .NET 7, because, incidentally, GitHub happens to build runner images with .NET 7 already installed.
https://github.com/erikdesj/setup-dotnet-test/actions/runs/3550078279

![image](https://user-images.githubusercontent.com/59450623/204040227-a92af97b-d3b3-4f7f-9eba-dbe7eac61c6f.png)

**Expected behavior:**
When the user writes the following,
```yml
- uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 5.0.x
```
the default dotnet SDK version is set to .NET 5.0.x, since that is what the user requested.

**Actual behavior:**
The default dotnet SDK version is rolled forward to the latest SDK version that's already installed.

---

I assume you're not actually going to change the v3 behavior, despite it being inconsistent with other (maybe all?) `actions/setup-*` actions, but the readme examples should be updated to work with the new behavior.

(For instance, both `setup-node` and `setup-java` will override the default to the version the user specifies, regardless of what's already installed. This is important to have a reliable CI process, because your tooling shouldn't suddenly change when the runner image is updated. Especially in GitHub Actions, where most users are not managing their own CI environments, they just get whatever tools GitHub happens to put in the latest image build. But I digress.)
