### ISSUE TITLE
`setup-dotnet` does not affect which version of dotnet CLI is used

### ISSUE THREAD

**Issue by DarkWanderer** [actions/setup-dotnet#354]
**Description:**
With following Actions job:
```
jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
    - run: dotnet --version
```
dotnet shows latest version - `7.0.100`

**Task version:**
`v3`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
See description

**Expected behavior:**
I would have expected `dotnet` to use version `6.x` as specified

**Actual behavior:**
Version `7.0.100` is run
