### ISSUE TITLE
Error with output XML

### ISSUE THREAD

**Issue by Daniel127** [actions/setup-dotnet#36]
I have the basic build, but when I activate the output of an XML document it fails

```
name: Github CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-rc1-014190
    - name: Build with dotnet
      run: dotnet build --configuration Release
```

Error:
> CSC : error CS0016: Could not write to output file '/QD.Components.Semantic.xml' -- 'Access to the path '/QD.Components.Semantic.xml' is denied.' [/home/runner/work/SemanticUI-Razor-Components/SemanticUI-Razor-Components/QD.Components.Semantic/QD.Components.Semantic.csproj]
