### ISSUE TITLE
global-json-file input does not accept absolute paths

### ISSUE THREAD

**Issue by othmane-kinane-nw** [actions/setup-dotnet#378]
**Description:**
`setup-dotnet` does not handle correctly absolute paths as value for the `global-json-file` input. The action always join the provided value with the github workspace (aka respository's root) instead of using it as-is if it's an absolute path.

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Pass an absolute path as value for the `global-json-file` input that points to a `global.json` file in a subfolder.
Do not use the `dotnet-version` input.
ex:
```yaml
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: ${{ github.workspace }}/backend/global.json
```

**Expected behavior:**
The action finishes with success and the provided `global.json` is used.

**Actual behavior:**
The action fails with this error:
```
Error: The specified global.json file '/home/runner/work/reponame/reponame/backend/global.json' does not exist
```
