### ISSUE TITLE
Workflow stuck in infinite loop when specifying multiple target systems.

### ISSUE THREAD

**Issue by 766F6964** [actions/setup-dotnet#38]
It seems that specifying multiple target systems for the `run-on` parameter triggers an infinite loop when setting up the workflow.

The following .yml file was used:
```
name: DotNETCore Build

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest, windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build CICDTest --configuration Release
    - name: Unit Tests
      run: dotnet test CICDTest 
```
When specifying either `ubuntu-latest` or `windows-latest` as target systems the workflow kicks of just fine. When specifying both, the workflow is stalls at `Starting your workflow run...` without any logs. It also seems not possible to abort the run once it is stuck.

EDIT: 5h later the process is still stuck at "Starting your workflow run..."
![ci](https://user-images.githubusercontent.com/34845270/65375531-01360280-dc97-11e9-9d9f-74a428d6f61c.png)
