### ISSUE TITLE
[Info] dotnet ^7.0.2* introduced an MSBuild preview version with breaking changes.

### ISSUE THREAD

**Issue by snwflake** [actions/setup-dotnet#383]
**Description:**
For reference: https://github.com/dotnet/sdk/issues/30624

The MSBuild preview version provided with 7.0.200 introduced breaking changes and generally [ill-formed behavior](https://github.com/dotnet/razor/issues/8281).

Pinning the version to anything below 7.0.200, ie. 7.0.103 does not resolve that issue, as the same MSBuild preview is still being used.

My workaround so far has been to add another step after the dotnet-setup which just removes 7.0.2* sdk versions. Only then started my build to produce working output with proper viewcomponents.

**Task version:**
[926f442](https://github.com/actions/setup-dotnet/commit/926f4420227aaf87acf2840f360e4f2475f13b3b)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
```yml
- name: Setup .net
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 7.0.103
```

```
dotnet publish app -c Release -o ~/deploy
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
```

**Notes:**
While this is a bug introduced by the SDK, I still wanted to raise this issue here, to spare others from wasting 3 hours debugging it.
The workaround for me is currently the following until the [announced hotfix 7.0.201](https://github.com/dotnet/sdk/issues/30624#issuecomment-1435408741) goes live:

```yml
- name: Setup .net
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: 7.0.103
- name: Remove faulty SDK version
  run: sudo rm -rf /usr/share/dotnet/sdk/7.0.2*
```
