### ISSUE TITLE
Requesting 7.0.x does not install 7.0.201

### ISSUE THREAD

**Issue by Shane32** [actions/setup-dotnet#388]
**Description:**
Specifying version 7.0.x does not install 7.0.201

Microsoft has stated that 7.0.201 is available in GitHub Actions:
- https://github.com/dotnet/sdk/issues/30625#issuecomment-1445175355

See workflow run:
- https://github.com/graphql-dotnet/graphql-dotnet/actions/runs/4268295374/jobs/7437302763

**Task version:**
`actions/setup-dotnet@v3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Add to workflow:
```
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
```

**Expected behavior:**
.NET SDK 7.0.201 is installed

**Actual behavior:**
.NET SDK 7.0.200 is used
