### ISSUE TITLE
Question - is this expected behavior or is my self-hosted Windows runner's issue?

### ISSUE THREAD

**Issue by erkexzcx** [actions/setup-dotnet#417]
This is not a bug report, but rather consultation. I am using self-hosted Windows runner. Ephemeral one, in AWS. Please advise if this is intended behavior when PATH is not updated on Windows runners or is it an issue from my side (miconfiguration/lack of permissions)? No errors are thrown...

----

Here is the simple CI/CD workflow I am trying to run:
```yaml
    steps:  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x

      - name: Print dotnet version (using PATH, ignore error)
        continue-on-error: true
        run: |
          dotnet.exe --version

      - name: Print dotnet version (using fullpath to executable)
        run: |
          & "C:\Program Files\dotnet\dotnet" --version
```

The output is this:

* **Setup .NET** - OK, but it prints interesting detail `dotnet-install: Adding to current process PATH: "C:\Program Files\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.`.

* **Print dotnet version (using PATH, ignore error)** - fails with `dotnet.exe : The term 'dotnet.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`.

* **Print dotnet version (using fullpath to executable)** - OK. Works as expected.

----

Please advise if this is expected behavior on Windows runners or is there some kind of misconfiguration/lack of permissions from my side?
