### ISSUE TITLE
dotnet 8 RC2 is not default for 8 preview

### ISSUE THREAD

**Issue by AceHack** [actions/setup-dotnet#472]
**Description:**
```
    # sets up .NET Core SDK 8
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
        dotnet-quality: 'preview'
```

Should pull in 8 RC2 not RC1

**Task version:**
actions/setup-dotnet@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
See above usage

**Expected behavior:**
dotnet 8 RC2 SDK

**Actual behavior:**
dotnet 8 RC1 SDK
