### ISSUE TITLE
Error The NUGET_AUTH_TOKEN was not provided after upgrade from V3 to V4

### ISSUE THREAD

**Issue by lanwin** [actions/setup-dotnet#490]
**Description:**
We got an dependabot upgrade pullrequest from v3 to v4. V3 works without a problem. V4 raises an error:

> Error: The NUGET_AUTH_TOKEN environment variable was not provided. In this step, add the following: 

But NUGET_AUTH_TOKEN is provided and works with v3.

**Task version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
```yaml
jobs:
  dotnet:
    runs-on: [self-hosted, linux]
    env:
      TZ: Europe/Amsterdam
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_INSTALL_DIR: "./.dotnet"
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x.x
          source-url: https://nuget.pkg.github.com/xxxx/index.json
      - run: dotnet restore
      - run: dotnet build --no-restore
```

**Comment by dusan-trickovic** [comment]
Hello, @lanwin! Thank you for reporting this issue, we will look into it and see what can be done :)

**Comment by aparnajyothi-y** [comment]
Hello, @lanwin! Unfortunately, we couldn’t reproduce this issue. On our side the action executes successfully if the NUGET_AUTH_TOKEN is supplied.
Could you please share the failed workflow link from your repository to confirm the reproduction steps? Thank you in advance.

**Comment by lanwin** [comment]
@aparnajyothi-y thank you for your response. The problem is that this run ins in a private organization repository.

Btw here is a log from that "Setup .NET" step:

> Run actions/setup-dotnet@v4
>   with:
>     dotnet-version: 7.x.x
>     source-url: https://nuget.pkg.github.com/xxxx/index.json
>     cache: false
>   env:
>     TZ: Europe/Amsterdam
>     DOTNET_NOLOGO: true
>     DOTNET_CLI_TELEMETRY_OPTOUT: true
>     DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
>     DOTNET_INSTALL_DIR: ./.dotnet
>     NUGET_AUTH_TOKEN: 
> /runner/_work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --runtime dotnet --channel LTS
> dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.0/dotnet-runtime-8.0.0-linux-x64.tar.gz
> dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.0/dotnet-runtime-8.0.0-linux-x64.tar.gz size is 31389185 bytes.
> dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.0/dotnet-runtime-8.0.0-linux-x64.tar.gz
> dotnet-install: Downloaded file size is 31389185 bytes.
> dotnet-install: The remote and local file sizes are equal.
> dotnet-install: Installed version is 8.0.0
> dotnet-install: Adding to current process PATH: `/runner/_work/xxxx/xxxx/.dotnet`. Note: This change will be visible only when sourcing script.
> dotnet-install: Note that the script does not resolve dependencies during installation.
> dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
> dotnet-install: Installation finished successfully.
> /runner/_work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --channel 7.0
> dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.404/dotnet-sdk-7.0.404-linux-x64.tar.gz
> dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.404/dotnet-sdk-7.0.404-linux-x64.tar.gz size is 219088775 bytes.
> dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.404/dotnet-sdk-7.0.404-linux-x64.tar.gz
> dotnet-install: Downloaded file size is 219088775 bytes.
> dotnet-install: The remote and local file sizes are equal.
> dotnet-install: Installed version is 7.0.404
> dotnet-install: Adding to current process PATH: `/runner/_work/xxxx/xxxx/.dotnet`. Note: This change will be visible only when sourcing script.
> dotnet-install: Note that the script does not resolve dependencies during installation.
> dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
> dotnet-install: Installation finished successfully.
> dotnet-auth: Finding any source references in /runner/_work/xxxx/xxxx/nuget.config, writing a new temporary configuration file with credentials to /runner/_work/xxxx/nuget.config
> Error: The NUGET_AUTH_TOKEN environment variable was not provided. In this step, add the following: 
> env:
>   NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

Did that help?

**Comment by aparnajyothi-y** [comment]
Thank you for the quick response @lanwin !

Unfortunately, we couldn’t reproduce this issue. On our side the action executes successfully if the NUGET_AUTH_TOKEN is supplied.
I am seeing the NUGET_AUTH_TOKEN: is empty from the log that you have provided and we are able to see the NUGET_AUTH_TOKEN: *** from our log with the same Setup .NET" step if the NUGET_AUTH_TOKEN is supplied.
Please try to add and run the below line of code before Setup .Net step which helps to check whether NUGET_AUTH_TOKEN is available or not.

   - run: |
          [[ -z "${NUGET_AUTH_TOKEN}" ]] && echo 'does not exist' || echo "exists"
          
      Please find the screenshots for reference if we don't have NUGET_AUTH_TOKEN  supplied and If you have any other concerns regarding install-script running twice, please feel free to share them!
      
<img width="1390" alt="image" src="https://github.com/actions/setup-dotnet/assets/147696841/f800d63d-8be2-4151-9f6d-3bae91ac6c62">

<img width="1369" alt="image" src="https://github.com/actions/setup-dotnet/assets/147696841/2fc25bc7-7600-4b68-9acf-ab0b34550d31">

**Comment by aparnajyothi-y** [comment]
Hello @lanwin, just a gentle ping.

**Comment by lanwin** [comment]
Thanks for the reminder. Currently a little bit too much on my desk. I try to check that soon.

**Comment by lanwin** [comment]
So I tested that and I am a little bit confused.

![grafik](https://github.com/actions/setup-dotnet/assets/15905/5d1474a3-6de9-48e3-84e3-83e22a1830b2)

I run the previous state and it failed. After adding your run command and committing it to the branch it starts working and the *** are visible now. Also when I am remove the run command again.

**Comment by asbjornu** [comment]
This configuration: 

```yaml
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/OWNER/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Caused the following error for me:

> No API Key was provided and no API Key could be found for 'https://nuget.pkg.github.com/OWNER'. To save an API Key for a source use the 'setApiKey' command.

What I had to do was to remove `source-url` and `NUGET_AUTH_TOKEN` and instead pass them to `dotnet nuget push` like so:

```sh
dotnet nuget push *.nupkg --api-key "${{ secrets.GITHUB_TOKEN }}" --source "https://nuget.pkg.github.com/OWNER/index.json"
```
