### ISSUE TITLE
Allow specifying 'latest' as dotnet-version

### ISSUE THREAD

**Issue by CamJN** [actions/setup-dotnet#497]
**Description:**
A workflow with the following would install the latest major version of dotnet.
```
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: latest
```

**Justification:**
It would be nice to be able to just stick `latest` in the dotnet-version field and not have to update the tag when a new major version comes out. This is available in the node and ruby setup actions and is quite nice.

**Are you willing to submit a PR?**
Unlikely.

**Comment by kevinoid** [comment]
I'd also appreciate this feature.  For reference, it is currently possible to install the latest LTS version with:

```yaml
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: x
```

Unfortunately, this always installs a version from the LTS channel due to

https://github.com/actions/setup-dotnet/blob/3e891b0cb619bf60e2c25674b222b8940e2c1c25/src/installer.ts#L77-L78
