### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by dmstrat** [actions/setup-dotnet#503]
**Description:**
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-dotnet@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Task version:**
v2 

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Run Action

**Expected behavior:**
Action runs using Node.js version 20+ 

**Actual behavior:**
Action runs using Node.js version 16

**Comment by aparnajyothi-y** [comment]
Hello @dmstrat
Thank you for creating this issue and we will look into the issue :)

**Comment by Werebunny** [comment]
Note this happens on all platforms and not just Ubuntu.

**Comment by SimonBrettschneider** [comment]
I can confirm it also happens on Windows.

**Comment by mauricio-tamez** [comment]
The latest version of setup-dotnet is v4, have you tried updating your workflow to use setup-dotnet@v4 ? That solved the issue for me.

**Comment by gabrielweyer** [comment]
#502 updates the README to use the latest version.

**Comment by dmstrat** [comment]
This is no longer a bug but a documentation issue that #502 seems to fix once merged.

**Comment by adriaanbalt** [comment]
I'm using the generated Firebase YAML file for Hosting.  It looks like this:
```
name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd packages/website && yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIEMOOD_6C59F }}'
          channelId: live
          projectId: coolprojectname
```

the default uses ` actions/checkout@v3` but I've changed it to ` actions/checkout@v4`.  I'm still getting this error in Github workflow actions:

[build_and_deploy](https://github.com/adriaanbalt/GREATFLIX/actions/runs/8308530068/job/22738866328)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: FirebaseExtended/action-hosting-deploy@v0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I'm not using Docker so I'm not sure if I need to use `docker/setup-buildx-action@v2`
