### ISSUE TITLE
Support SDK workloads 

### ISSUE THREAD

**Issue by timheuer** [actions/setup-dotnet#523]
**Description:**
The SDK ships with supporting a set of workloads (Wasm, MAUI, Aspire, and potentially more in the future).  The `setup-dotnet` action should support these as further instructions to actually 'setup' the full dotnet environment as expected, not automatically, but opt-in.

```yaml
uses: actions/setup-dotnet@v5
with:
  dotnet-version: 8.0.x
  workloads: [maui, aspire]
```

The expectation is that after SDK would be installed that then command would run `dotnet workload update` (to ensure manifests are updated) and then `dotnet workload install` on each item in the array

**Justification:**
Workloads are a primary way to get additional platform SDK tools and dependencies for key .NET frameworks.

/cc @baronfel

**Comment by baronfel** [comment]
Love this - one implementation note is that the list of workloads provided can be supplied to `dotnet workload install` all in one go, because the command takes an array of workloads. This should result in a performance improvement.

One subtlety to the situation is that instead of installing various workloads, we also support `dotnet workload restore` to acquire the workloads that a given solution or project require - that would be less 'variable' (meaning you wouldn't have to update the list of workloads).

**Comment by HarithaVattikuti** [comment]
Hello @timheuer
Thank you for creating this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by Redth** [comment]
There's also now the concept of workload sets....  So, you can install a particular workload set by the version.  I would suggest anything done here should (optionally) support specifying a version (pattern)...

```yaml
uses: actions/setup-dotnet@v5
with:
  dotnet-version: 9.0.x
  workloads:
    version: 9.0.x
    ids: [maui, aspire]
```

which basically would run `dotnet workload install --version 9.0.103 maui aspire`
