### ISSUE TITLE
Support explicit architecture for dotnet

### ISSUE THREAD

**Issue by ww898** [actions/setup-dotnet#524]
**Description:**
I need to install both arm64 and x64 architectures for .NET 8.0 on macOS M1 for execute tests on different platforms. Now it checks only arm64 version and say that everything was already installed.

**Justification:**
Example of the new symtax:
```
        uses: actions/setup-dotnet@v4
        with:
          dotnet:
            - version: 8.0.x
               arch: x64
            - version: 8.0.x
               arch: arm64
```
