### ISSUE TITLE
Docs Bug: v4 README points to v3

### ISSUE THREAD

**Issue by dluc** [actions/setup-dotnet#527]
URL: https://github.com/actions/setup-dotnet/tree/v4

[README](https://github.com/actions/setup-dotnet/blob/v4/README.md) content:

![image](https://github.com/actions/setup-dotnet/assets/371009/5b98ee79-f247-4504-80ec-0c345b8a6e27)

should be

```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-dotnet@v4
  with:
    dotnet-version: '3.1.x'
- run: dotnet build <my project>
```
