### ISSUE TITLE
Infrequent "MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found" errors with ubuntu 24.04 hosted runner.

### ISSUE THREAD

**Issue by foriequal0** [actions/setup-dotnet#531]
**Description:**

Infrequent 'MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found' with ubuntu 24.04 hosted runner.
The error happens in projects with `<Project Sdk="Microsoft.NET.Sdk.Web">` only (`<Project Sdk="Microsoft.NET.Sdk">` are fine)

**Task version:**
v4.0.0

**Platform:**
- [x] Ubuntu (24.04)
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

actions:
```yaml
  test:
    runs-on: [ubuntu-24.04]
    env:
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 1
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.0.x"
        timeout-minutes: 1
      - run: dotnet restore
      - run: dotnet build --no-restore
```

global.json:
```json
{
  "sdk": {
    "version": "7.0.202",
    "rollForward": "latestFeature"
  }
}
```

some-proj.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  ...

</PropertyGroup>
```

Trigger the action.

**Expected behavior:**
build succeed.

**Actual behavior:**

Sometime build error only on projects with "Microsoft.NET.Sdk.Web"
```
/home/runner/work/.../some-proj1.csproj : error : Could not resolve SDK "Microsoft.NET.Sdk.Web". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
/home/runner/work/.../some-proj2.csproj : error :   
/home/runner/work/.../some-proj3.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
/home/runner/work/.../some-proj4.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
...
    0 Warning(s)
    20 Error(s)
```

This is the setup-dotnet action log
```
/home/runner/work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --runtime dotnet --channel LTS
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.6/dotnet-runtime-8.0.6-linux-x64.tar.gz
dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.6/dotnet-runtime-8.0.6-linux-x64.tar.gz size is 31270581 bytes.
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.6/dotnet-runtime-8.0.6-linux-x64.tar.gz
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
dotnet-install: Downloaded file size is 31270581 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Installed version is 8.0.6
dotnet-install: Adding to current process PATH: `/usr/share/dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
/home/runner/work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --channel 7.0
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.410/dotnet-sdk-7.0.410-linux-x64.tar.gz
dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.410/dotnet-sdk-7.0.410-linux-x64.tar.gz size is 218499912 bytes.
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.410/dotnet-sdk-7.0.410-linux-x64.tar.gz
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
dotnet-install: Downloaded file size is 218499912 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Installed version is 7.0.410
dotnet-install: Adding to current process PATH: `/usr/share/dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
```

**Comment by aparnajyothi-y** [comment]
Hello @foriequal0, Thank you for creating this issue and we will look into it :)

**Comment by aparnajyothi-y** [comment]
Hello @foriequal0, We have investigated on this issue and unfortunately we are unable to reproduce the issue from our end in this [workflow run](https://github.com/setup-actions-demo/test-setup-dotnet/actions/runs/9852227794/job/27200370336). Please share your repro link to investigate the issue as it is not consistent.

Hello @abrousseau-hcgov, We have investigated the issue and found that the .NET Core SDK version '8.0.302' is being reused from the cache instead of downloading and installing it anew.  The issue can be caused if the cached file is partially downloaded or corrupted. Workaround to resolve the codeQL scan failures ensure that the cache is cleared before the installed step either through workflow or manually. Please use the below step to clear cache through workflow. Please let us know in case of any further clarifications or the issue still persists.

- name: Clear cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache
          # Add any other paths you want to clear
        key: ${{ runner.os }}-clear-cache-${{ github.sha }}

**Comment by foriequal0** [comment]
Hi. It happened in our team's private repo so I couldn't share the link.
It seems that the issue isn't reproduced for us anymore.

**Comment by aparnajyothi-y** [comment]
Hello @foriequal0, Thank you for confirming the issue is not reproducible from your end also and actions/setup-dotnet is working successfully. 
We are proceeding to close this issue for now and please feel free to reach us to reopen this issue in case of any further assistance/support needed.

**Comment by foriequal0** [comment]
I should re-open this issue since it happened again just a few minutes ago.
this is the log when it failed (it is not different from the log when it doesn't fail)
```
Run actions/setup-dotnet@v4
  with:
    dotnet-version: 7.0.x
    source-url: https://nuget.pkg.github.com/shiftupcorp/index.json
    cache: false
  env:
    NUGET_AUTH_TOKEN: ***
/home/runner/work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --runtime dotnet --channel LTS
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.7/dotnet-runtime-8.0.7-linux-x64.tar.gz
dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.7/dotnet-runtime-8.0.7-linux-x64.tar.gz size is 31272597 bytes.
dotnet-install: Extracting archive from https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.7/dotnet-runtime-8.0.7-linux-x64.tar.gz
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
dotnet-install: Downloaded file size is 31272597 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Installed version is 8.0.7
dotnet-install: Adding to current process PATH: `/usr/share/dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
/home/runner/work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --channel 7.0
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.410/dotnet-sdk-7.0.410-linux-x64.tar.gz
dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.410/dotnet-sdk-7.0.410-linux-x64.tar.gz size is 218499912 bytes.
dotnet-install: Extracting archive from https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.410/dotnet-sdk-7.0.410-linux-x64.tar.gz
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
dotnet-install: Downloaded file size is 218499912 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Installed version is 7.0.410
dotnet-install: Adding to current process PATH: `/usr/share/dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
dotnet-auth: Finding any source references in /home/runner/work/nk-backend/nk-backend/NuGet.Config, writing a new temporary configuration file with credentials to /home/runner/work/nk-backend/nuget.config
```

I think it might be related to the simultaneous installation of 8.0 runtime, and 7.0 SDK.
