### ISSUE TITLE
Proxy Setup fail with self-hosted runner

### ISSUE THREAD

**Issue by yannou38** [actions/setup-dotnet#558]
**Description:**
When trying to use the action, i get an error when the action try to set the proxy object

```
New-Object : La valeur fournie n'est pas valide ou la propriété est en lecture seule. Modifiez la valeur, puis 
réessayez.
Au caractère C:\ghr\IOTSEC-gh-actions\1\_work\_actions\actions\setup-dotnet\c7e7147fd3e41056e75a761416c06f5fa781b5fb\ex
ternals\install-dotnet.ps1:366 : 45
  ... ttpClientHandler.Proxy =  New-Object System.Net.WebProxy -Property @{
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      CategoryInfo          : InvalidData : (:) [New-Object], Exception
      FullyQualifiedErrorId : SetValueException,Microsoft.PowerShell.Commands.NewObjectCommand
```

**Task version:**
commit id c7e7147fd3e41056e75a761416c06f5fa781b5fb

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Repro steps:**  
- Set a proxy in system env variable on your selfhosted runner
- run action
```
- name: test setup dotnet
        id: testdotnet
        uses: actions/setup-dotnet@c7e7147fd3e41056e75a761416c06f5fa781b5fb
        with:
          dotnet-version: '7'
```
**Expected behavior:**
Proxy should be set and dotnet should get downloaded

**Actual behavior:**
Error pasted above
