### ISSUE TITLE
GitHub Actions Failing to Build .NET 9.0 Project

### ISSUE THREAD

**Issue by ZjzMisaka** [actions/setup-dotnet#562]
**Description:**
I recently updated my project to target .NET 9.0 after its release. I modified the csproj file to set the TargetFramework to .NET 9.0 and successfully built the project on my local machine. However, after committing the changes, the GitHub Actions workflow fails during the build step with the following error:
```
The current .NET SDK does not support targeting .NET 9.0. Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download
```
This suggests that the version of the .NET SDK being used in the GitHub Actions environment does not yet support .NET 9.0.

Questions: 
1. Is .NET 9.0 supported in GitHub Actions?
2. Do I need to configure my workflow specifically for .NET 9.0?

**Task version:**
actions/setup-dotnet@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
https://github.com/ZjzMisaka/PowerThreadPool/blob/main/.github/workflows/test.yml

**Expected behavior:**
Successfully build

**Actual behavior:**
Build step with the following error:
```
The current .NET SDK does not support targeting .NET 9.0. Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download
```

**Comment by aparnajyothi-y** [comment]
Hello @ZjzMisaka, Thank you for creating this issue and we will look into it :)

**Comment by ZjzMisaka** [comment]
> Hello @ZjzMisaka, Thank you for creating this issue and we will look into it :)

Hi, thank you for the help, is there any progress, or something need my help?

**Comment by mahalakshmi-rekadi** [comment]
Hello @ZjzMisaka,
GitHub Actions supports .NET 9.0, but to use it, you need to install it externally and configure your workflow to use the correct SDK version. Since ubuntu-latest runners support up to .NET 8.0 version, you need to specify the .NET 9.0 SDK version in  actions/setup-dotnet@v4 step.

Workflow Configuration:
To resolve this, update your workflow file to specify the .NET 9.0 SDK version as shown below:

steps:
  - uses: actions/checkout@v4
    name: Checkout code
  - name: Setup .NET
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 9.0.x
  - name: Restore dependencies
    run: dotnet restore PowerThreadPool/PowerThreadPool.csproj
  - name: Build
    run: dotnet build PowerThreadPool/PowerThreadPool.csproj --no-restore

1.The specified Target Framework Monikers (TFMs) indicate compatibility with multiple .NET versions.
2.The .NET SDK version in the workflow determines the highest framework version supported during the build process.
3.Using the .NET 9.0 SDK ensures compatibility with all specified TFMs, including the newest framework versions.

For more details, refer to the [Select which .NET version to use - .NET | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/core/versions/selection).

Please let us know if you have any further questions or need additional support

**Comment by hongbo-miao** [comment]
Hi @mahalakshmi-rekadi similar to yours, we specified sdk version `9.0.100`

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up NuGet
        uses: nuget/setup-nuget@v2.0.1
        with:
          nuget-version: 6.12.1
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          global-json-file: hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge/global.json
      - name: Install dependencies
        working-directory: hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge
        run: |
          nuget restore VeriStandZeroMQBridge.sln
          dotnet tool restore
      - name: Lint C# (format)
        working-directory: hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge
        run: |
          dotnet format VeriStandZeroMQBridge.sln --verify-no-changes
```

and this `hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge/global.json` content is

```json
{
  "sdk": {
    "version": "9.0.100",
    "quality": "release"
  }
}
```

Here is the failed [build](https://github.com/hongbo-miao/hongbomiao.com/actions/runs/11995672614/job/33439228289?pr=20733).

What is the difference with yours?

**Comment by ZjzMisaka** [comment]
@mahalakshmi-rekadi Thank you, your suggestion works well. However, I’d like to know if the ubuntu-latest runner will support .NET 9.0 in the near future? 
If native support for .NET 9.0 becomes available, I can re-run the previously failed Actions. While new GitHub Actions are running successfully, the failed ones remain in a failed state.

**Comment by hongbo-miao** [comment]
Hi @ZjzMisaka which step helped? Did I miss anything from @mahalakshmi-rekadi ? Could you share? Thanks!

**Comment by hongbo-miao** [comment]
Hi @ZjzMisaka did you succeed on Ubuntu 22.04? Thanks!

In my case, I failed on Ubuntu 22.04 with sdk 9.0.100. Here is my [build](https://github.com/hongbo-miao/hongbomiao.com/actions/runs/11995672614/job/33439228289?pr=20733)

![image](https://github.com/user-attachments/assets/64d2961e-6dfd-4c48-be23-39bc6610499b)

**Comment by hongbo-miao** [comment]
Oh I saw @ZjzMisaka 's change at https://github.com/ZjzMisaka/PowerThreadPool/pull/81/files and succeed. Strange, mine still failed, I will test more and if still no luck, will create a new ticket. Thanks!

**Comment by ZjzMisaka** [comment]
@hongbo-miao I'm not sure but maybe you should try to add this? 
```
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
```
