### ISSUE TITLE
Sometimes got error "Unable to locate dotnet CLI. Ensure that it is on the PATH"

### ISSUE THREAD

**Issue by hongbo-miao** [actions/setup-dotnet#564]
**Description:**

I found `setup-dotnet` is not always reliable.

For example, in same GitHub Action build:

- `Attempt #1` failed: https://github.com/hongbo-miao/hongbomiao.com/actions/runs/12211957209/attempts/1
- `Attempt #2` succeed: https://github.com/hongbo-miao/hongbomiao.com/actions/runs/12211957209

> Unable to locate dotnet CLI. Ensure that it is on the PATH.

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up NuGet
        uses: nuget/setup-nuget@v2.0.1
        with:
          nuget-version: 6.12.1
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          global-json-file: hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge/global.json
      - name: Install dependencies
        working-directory: hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge
        run: |
          nuget restore VeriStandZeroMQBridge.sln
          dotnet tool restore
      - name: Lint C# (format)
        working-directory: hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge
        run: |
          dotnet format VeriStandZeroMQBridge.sln --verify-no-changes
      - name: Lint C# (CSharpier)
        working-directory: hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge
        run: |
          dotnet csharpier --check .
```

hardware-in-the-loop/national-instruments/veristand/VeriStandZeroMQBridge/global.json
```json
{
  "sdk": {
    "version": "8.0.404"
  }
}
```

**Expected behavior:**

I expect dotnet CLI work all time if no code changes.

**Actual behavior:**

Even same code in same build, sometimes I got error "Unable to locate dotnet CLI. Ensure that it is on the PATH"

Also, for this [pull request](https://github.com/hongbo-miao/hongbomiao.com/pull/21328), when bumping csharpier from 0.30.2 to 0.30.3, no matter how many times I tried, I always got

> Unable to locate dotnet CLI. Ensure that it is on the PATH

[Build log](https://github.com/hongbo-miao/hongbomiao.com/actions/runs/12216500602/job/34081882497?pr=21328)

![image](https://github.com/user-attachments/assets/f323958f-2bd3-443a-8b55-2b52f42a9e54)

You can see dotnet CLI got installed at `C:\Program Files\dotnet`, but next step it says cannot find it

> Unable to locate dotnet CLI. Ensure that it is on the PATH.
