### ISSUE TITLE
Action doesn't complete installation of dotnet on macos

### ISSUE THREAD

**Issue by Yury-Fridlyand** [actions/setup-dotnet#608]
**Description:**
Installation on macos isn't completed as it happens on linux runner.
In order to keep CI jobs working properly, we have to do extra steps just to ensure that proper version of SDK is used. That increases complexity and maintenance costs.

**Task version:**
`v4`

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
```yml
jobs:
    experiment:
        runs-on: macos-14
        steps:
            - name: check
              run: |
                  dotnet --info || true
                  which dotnet || true
            - name: Set up dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '6.0'
            - name: check
              run: |
                  dotnet --info || true
                  which dotnet || true
```

**Expected behavior:**
On macos runner, `Base path` [remains unchanged](https://github.com/valkey-io/valkey-glide/actions/runs/13666910596/job/38209887450#step:4:46) and refers to incorrect sdk version
```
 Base Path:   /Users/runner/.dotnet/sdk/9.0.102/
```

**Actual behavior:**
On linux runner, `Base path` changes after running the action from
```
 Base Path:   /usr/lib/dotnet/sdk/8.0.112/
```
[to](https://github.com/valkey-io/valkey-glide/actions/runs/13666927856/job/38209936051#step:4:21)
```
 Base Path:   /usr/share/dotnet/sdk/6.0.428/
```
