### ISSUE TITLE
Using v1.0.0 fails to get correct SDK requested

### ISSUE THREAD

**Issue by timheuer** [actions/setup-dotnet#61]
This:
```
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.0.0
        with:
          dotnet-version: 3.1.100
```
fails to actually get the 3.1.100 SDK, however:
```
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
```
works correctly.

The @v1.0.0 is what is suggested use on the marketplace listing.
