### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by CaseyHofland** [actions/setup-dotnet#617]
**Description:**
I have the following github action for building and testing my new open source project.
```
name: dotnet package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '8.0.x']

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet ${{matrix.dotnet-version}}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{matrix.dotnet-version}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
```

When it gets to the `Restore dependencies` step on the `3.1.x` build, it fails with the following error:
```
Run dotnet restore
  dotnet restore
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /usr/share/dotnet
No usable version of libssl was found
/home/runner/work/_temp/f21adc59-df1d-49aa-bf25-d7a6bb0f0055.sh: line 1:  2298 Aborted                 (core dumped) dotnet restore
Error: Process completed with exit code 134.
```

The only advice on fixing `No usable version of libssl was found` I could find was to [specify the latest version](https://dev.to/n3wt0n/no-usable-version-of-the-libssl-was-found-solved-2ffa) of the failing dotnet-versions, which I did and subsequently yielded no results (incredible I know).

I have seen this issue been addressed in issue #176 where the solution was to simply "remove unsupported versions", in my case simply removing `3.1.x`. However, my project targets the frameworks .NET 8 and .NET Standard 2.1 so it can run on Unity. Building and Testing on .NET Core 3.1 is an absolute must for me. What can I do to fix it?

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Comment by gowridurgad** [comment]
Hi @CaseyHofland,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by CaseyHofland** [comment]
To provide a bit more information as I'm learning, I have been hard at work reading up on more sources. And I wanted to explain my use case in a little more detail, to make sure I'm not missing the mark.

My project is targeting multiple frameworks and has the following tag:
```
<TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
```

The test project in turn has this tag:
```
<TargetFrameworks>netcoreapp3.1;net8.0</TargetFrameworks>
```

(Since .NET Standard 2.1 is not an application it cannot run / execute, therefor the test project needs to run on .NET Core App 3.1).

What I want is to test that my project builds and runs correctly on both frameworks, namely .NET 8 and .NET Standard 2.1.

It is my assumption that to do this in my github action I need to setup both of these dotnet versions. But keep in mind that I am a novice when it comes to github actions, and fairly bad at debugging them.

If you have any questions for me I'll be soon to respond.

**Comment by CaseyHofland** [comment]
After some testing I realized I needed to change my github action to account for the fact that my project targets multiple frameworks (.NET 8 & .NET Core 3.1).

The new action looks like this:
```
name: dotnet package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
```

As can be seen, both versions are now installed side-by-side.

The error still occurs, though notably it now occurs during the `Test` step as opposed to the `Restore dependencies` step.

Here is the complete error log:
```
Run dotnet test --no-build --verbosity normal
  dotnet test --no-build --verbosity normal
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /usr/share/dotnet
Build started 03/19/[2](https://github.com/Cubusky/Cubusky.Core/actions/runs/13949994276/job/39046701258#step:7:2)025 15:10:50.
     1>Project "/home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.sln" on node 1 (VSTest target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|Any CPU".
Test run for /home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.Tests/bin/Debug/netcoreapp[3](https://github.com/Cubusky/Cubusky.Core/actions/runs/13949994276/job/39046701258#step:7:3).1/Cubusky.Core.Tests.dll (.NETCoreApp,Version=v3.1)
VSTest version 17.11.1 (x6[4](https://github.com/Cubusky/Cubusky.Core/actions/runs/13949994276/job/39046701258#step:7:4))

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No usable version of libssl was found
The active test run was aborted. Reason: Test host process crashed : No usable version of libssl was found


Test Run Aborted.
     1>Project "/home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.sln" (1) is building "/home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.Tests/Cubusky.Core.Tests.csproj" (3) on node 2 (VSTest target(s)).
     3>Project "/home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.Tests/Cubusky.Core.Tests.csproj" (3) is building "/home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.Tests/Cubusky.Core.Tests.csproj" (3:2) on node 2 (VSTest target(s)).
     3>_VSTestConsole:
         MSB4181: The "VSTestTask" task returned false but did not log an error.
     3>Done Building Project "/home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.Tests/Cubusky.Core.Tests.csproj" (VSTest target(s)) -- FAILED.
     3>DispatchToInnerBuildsWithVSTestTarget:
         Build continuing because "ContinueOnError" on the task "MSBuild" is set to "ErrorAndContinue".
Test run for /home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.Tests/bin/Debug/net8.0/Cubusky.Core.Tests.dll (.NETCoreApp,Version=v8.0)
VSTest version 17.11.1 (x64)

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.[5](https://github.com/Cubusky/Cubusky.Core/actions/runs/13949994276/job/39046701258#step:7:5)+1caef2f33e (64-bit .NET 8.0.14)
[xUnit.net 00:00:00.43] Skipping: Cubusky.Core.Tests (could not find dependent assembly 'Cubusky.Core, Version=1.0.0')
No test is available in /home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.Tests/bin/Debug/net8.0/Cubusky.Core.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

     3>Done Building Project "/home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.Tests/Cubusky.Core.Tests.csproj" (VSTest target(s)) -- FAILED.
     1>Done Building Project "/home/runner/work/Cubusky.Core/Cubusky.Core/Cubusky.Core.sln" (VSTest target(s)) -- FAILED.

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.[7](https://github.com/Cubusky/Cubusky.Core/actions/runs/13949994276/job/39046701258#step:7:8)8
Error: Process completed with exit code 1.
```

Take special note of the lines describing the error:
```
A total of 1 test files matched the specified pattern.
No usable version of libssl was found
The active test run was aborted. Reason: Test host process crashed : No usable version of libssl was found
```

As I'm learning more about this issue I understand it might be a problem with ubuntu rather than setup-dotnet. If this is not the right place to get my issue fixed, I'd like to know it.
