### ISSUE TITLE
10.0.x does not install .NET 10 preview.3

### ISSUE THREAD

**Issue by martincostello** [actions/setup-dotnet#625]
**Description:**

.NET 10 preview 3 was released yesterday, but for some reason actions/setup-dotnet is still installing .NET 10 preview **2** when `10.0.x` is passed to `dotnet-version`.

I wonder if there's something needs updating somewhere to do with the recent changes to the host name for the CDN where the .NET assets live?

I had a quick at the release notes JSON and also spotted this mistake, but I don't think that should affect the SDK install? https://github.com/dotnet/core/pull/9852

**Task version:**

v4.3.1

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

```yml
- name: Install .NET SDKs
  uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
  with:
    dotnet-version: |
      6.0.x
      8.0.x
      9.0.x
      10.0.x
```

**Expected behavior:**

Version `10.0.100-preview.3.25201.16` of the .NET SDK is installed.

**Actual behavior:**

Version `10.0.100-preview.2.25164.34` of the .NET SDK is installed.
