### ISSUE TITLE
Support for target runtimes.

### ISSUE THREAD

**Issue by JimBobSquarePants** [actions/setup-dotnet#72]
Looking at the documentation and the [code](https://github.com/actions/setup-dotnet/blob/b7821147f564527086410e8edd122d89b4b9602f/src/installer.ts#L47) it appears the SDK runtime platform architecture is determined by the architecture of the OS. 

It would be very useful for unit testing scenarios to allow specifying whether the x86 or x64 SDK is in use as `dotnet test` requires the explicit architecture.

**Comment by coderpatros** [comment]
From my looking it is explicitly set to [x64](https://github.com/actions/setup-dotnet/blob/7df9f59802b508a78c4e4e0f48c27ed646a9158c/src/installer.ts#L117)

It's probably a corner case, but it could cause issues if someone is running an x86 self hosted runner.

**Comment by AaronRobinsonMSFT** [comment]
Any thoughts resurrecting the following PR: https://github.com/actions/setup-dotnet/pull/152

I'd like a way to specify the architecture too. I need to test on win-x86 and setting that up is complicated.

**Comment by baynezy** [comment]
I need to test some code with x86 and so this is a blocker for me.

**Comment by brantburnett** [comment]
I have found a workaround I use in my workflows that's not TOO cumbersome. Note that this example assumes Windows for the OS.

```yaml
# This must be done before the normal setup-dotnet action to ensure DOTNET_ROOT refers to the 64-bit installation
- name: Setup .NET x86
  uses: actions/setup-dotnet@v4
  env:
    PROCESSOR_ARCHITECTURE: x86
    DOTNET_INSTALL_DIR: C:\Program Files (x86)\dotnet
  with:
    dotnet-version: 8.0.x

# Copy DOTNET_ROOT from the above step to DOTNET_ROOT(x86), the next step will overwrite DOTNET_ROOT to refer to the 64-bit installation
- name: Set DOTNET_ROOT(x86)
  shell: pwsh
  run: |
    echo "DOTNET_ROOT(x86)=${env:DOTNET_ROOT}" | Out-File -FilePath $env:GITHUB_ENV -Append
 
- name: Setup .NET
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: 8.0.x
```
