### ISSUE TITLE
Action fails for C# 8

### ISSUE THREAD

**Issue by KeithHenry** [actions/setup-dotnet#76]
I have a C# 8 project that uses C# 8 syntax

I have a simple action to build it:

```yml
name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
```

However, this throws an error whenever it encounters C# 8 syntax.

I _should_ be able to force the lang version in the `.csproj` file with `<LangVersion>8.0</LangVersion>`, but this errors with `CSC : error CS1617: Invalid option '8.0' for /langversion. Use '/langversion:?' to list supported values. [/home/runner/work/...myproject.csproj]`

How do I upgrade this action to compile a C#8 project?

**Comment by KeithHenry** [comment]
It appears that increasing the version to `dotnet-version: 3.1.100` does support the C# 8 syntax.

It looks like only the default C# version is supported for each `dotnet-version` setting, which is a problem for teams using Visual Studio 2019 to maintain .NET core 1.x and 2.x projects.

The C# version needs to be separate (or at least able to override the default) from the library version.

**Comment by litetex** [comment]
I think what you ask for does not belong here:

Take a look at https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version
> C# 8.0 (and higher) is supported only on .NET Core 3.x and newer versions.

**Comment by KeithHenry** [comment]
@litetex this is just one case of the issue - targeting older frameworks with different C# versions is common practice, especially during migration where you may want your CI to still function while you break down the upgrade job into manageable parts.

You should be able to specify the language version, not just C#8 with .NET Core 2

**Comment by litetex** [comment]
Sorry I really don't understand your problem.

> targeting older frameworks with different C# versions is common practice ...

As long as you use a C# version that is supported by the SDK this should work. 
[Net Core 2.1](https://dotnet.microsoft.com/download/dotnet-core/2.1) e.g. supports C# version <= 7.3, so a Net Core 1 project should work

<br/>

> You should be able to specify the language version

This is possible in the .csproj file:
```XML
<LangVersion>5</LangVersion>
```

Building a Net Core 1.0 (targeted framework)-project with LangVersion=5 works with the latest Net Core SDK 3.1:
* [project file](https://github.com/litetex/ConsoleApp1/blob/master/ConsoleApp1/ConsoleApp1.csproj) 
* [results of the GitHub action](https://github.com/litetex/ConsoleApp1/runs/571761999)

So this is definitely not a GitHub actions problem.

Or am I get something completely wrong?

**Comment by ZEisinger** [comment]
As litetex stated, 2.2 only supports C# versions <= 7.3. You have to use the proper sdk version for building C# 8. If you have further questions, the dotnet team would be the best source for resolving framework issues. See: https://github.com/dotnet/runtime#filing-issues

**Comment by plioi** [comment]
This happens even for a dotnet-version that IS compatible with C#8, such as `dotnet-version: 3.1.201`

**Comment by litetex** [comment]
@plioi 
Is there any more information?

If you mean this: https://github.com/fixie/fixie/actions/runs/114176975
Checkout this line of code: https://github.com/fixie/fixie/blob/develop/src/Fixie.Console/Fixie.Console.csproj#L5

*Flys away 🚀*

**Comment by plioi** [comment]
I wondered if that was the case, so I tried again with two invocations of setup-dotnet:

https://github.com/fixie/fixie/runs/704723182

Using the following definition:

```yml
name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core 2 (Deprecated `dotnet fixie` Support)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.806
    - name: Setup .NET Core 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - run: pwsh ./build.ps1
```

Windows and macOS runs succeed, Ubuntu fails with errors about missing C# 8. Both invocations of setup-dotnet appear to succeed.
