### ISSUE TITLE
Is there a list of the supported versions?

### ISSUE THREAD

**Issue by JasonFreeberg** [actions/setup-dotnet#77]
Is there a list (or derived list) of the supported versions? Our team hasn't had much success using this action to set up anything other than the version in the README (`2.2.108`).

I see that the action scans this [release metadata](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json) for available versions, and `3.0.2` is there. I tried specifying `3.0.2`, `3.0`, and `3.x` but none have worked. Is the problem with the OS (`ubuntu-latest`)?

```yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0
```

CC: @nertim @btardif @ehamai
