### ISSUE TITLE
Unauthenticated error when using example for Azure DevOps feed

### ISSUE THREAD

**Issue by Wouter8** [actions/setup-dotnet#79]
I'm trying to create a simple GitHub action which builds and tests my project. I have a private NuGet package which I'm hosting on an Azure Nuget feed. I saw this action should be compatible with it.

I added the secret (generated in Azure, added to GitHub settings) and tried running the workflow. Sadly I'm still getting a 401 error.

Am I missing something?

```
 steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        source-url: https://pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.AZURE_DEVOPS_PAT}}
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ${{env.workingDirectory}}
    - name: Test
      run: dotnet test
      working-directory: ${{env.workingDirectory}}
```

```
/opt/hostedtoolcache/dncs/3.1.100/x64/sdk/3.1.100/NuGet.targets(123,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/nuget/v3/index.json. [/home/runner/work/Wv8.Finance.Back-End/Wv8.Finance.Back-End/Wv8.Finance.Back-End/Wv8.Finance.Back-End.sln]
/opt/hostedtoolcache/dncs/3.1.100/x64/sdk/3.1.100/NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/home/runner/work/Wv8.Finance.Back-End/Wv8.Finance.Back-End/Wv8.Finance.Back-End/Wv8.Finance.Back-End.sln]
```
