### ISSUE TITLE
Setup dotnet with preview version (e.g. 5.0 preview 2)

### ISSUE THREAD

**Issue by nietras** [actions/setup-dotnet#83]
I would like to run this action using the .NET 5.0 preview, but this does not seem possible?

**Comment by litetex** [comment]
resolved in #80

**Comment by nietras** [comment]
@litetex I did try using the latest sdk version (as per https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json) in `yml` but this fails e.g.:
```yml
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnet: [ '5.0.100-preview.3.20216.6' ]
```
Am I specifying it wrong? :)
