### ISSUE TITLE
setup-dotnet can be run without any arguments -  confusing documentation

### ISSUE THREAD

**Issue by litetex** [actions/setup-dotnet#84]
From https://github.com/actions/setup-dotnet/issues/83#issuecomment-619420598

When using actions/**setup**-dotnet it  should **setup** dotnet.
However the source code says:
```JS
    //
    // Version is optional.  If supplied, install / use from the tool cache
    // If not supplied then task is still used to setup proxy, auth, etc...
    //

    let version = core.getInput('version');
    if (!version) {
      version = core.getInput('dotnet-version');
    }
    if (version) {
      const dotnetInstaller = new installer.DotnetCoreInstaller(version);
      await dotnetInstaller.installDotnet();
    }
```

However in the [documentation of the action](https://github.com/actions/setup-dotnet/blob/master/action.yml) is not written that the version is optional:
```
dotnet-version:
    description: 'SDK version to use. Example: 2.2.104'
source-url:
    description: 'Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword'
```

So if you don't supply ``version`` (doc says it is deprecated and should be removed since Oct 1, 2019) or ``dotnet-version`` it **does not setup dotnet**.
It just "configures" it. 
If there is nothing to configure, it exits without any error.
This can be very confusing if no version is supplied (as in #83 ), because **setup**-dotnet exits and the only thing that is setup is the [preinstalled ``dotnet``](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md)

In my expectation **setup**-dotnet should always **setup** dotnet.
If you want to do configurations like using another package source (parameters: ``source-url`` and ``config-file``) this should be outsourced into another action, e.g. setup-dotnet-package-source(-authentification)
