### ISSUE TITLE
Warning: Unexpected input 'dotnet-version'

### ISSUE THREAD

**Issue by pedrorohr** [actions/setup-dotnet#90]
Hi,

I've seen see the following message:
`##[warning]Unexpected input 'dotnet-version', valid inputs are ['version']`

It started a few days ago.

I've been using the Action this way:
```
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1.0.0
        with:
          dotnet-version: '2.2.402' # SDK Version to use.
```

Should I start to use `version` instead of `dotnet-version`?

**Comment by ZEisinger** [comment]
Please use version "v1". v1.0.0 is out of date and not supported.
```
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.402' # SDK Version to use.
```
