### ISSUE TITLE
Potential issue when using wildcarded `dotnet-version`

### ISSUE THREAD

**Issue by thashepherd** [actions/setup-dotnet#94]
See https://github.com/Aurora-Modders/AuroraLoader/runs/721995332?check_suite_focus=true using the following (snipped) workflow:

```
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet test
```

This resulted in the following:
![image](https://user-images.githubusercontent.com/711467/83312602-e847fe80-a1e0-11ea-8300-f209440e1d74.png)

Changing `dotnet-version` to `3.1.300` (and nothing else besides adding the `DOTNET_NOLOGO` environment variable) resulted in a successful build in https://github.com/Aurora-Modders/AuroraLoader/runs/722001214?check_suite_focus=true.
