### ISSUE TITLE
Wrong working directory for config-file

### ISSUE THREAD

**Issue by jeremy-marcus** [actions/setup-dotnet#96]
When adding a nuget package source auth token while providing a ```config-file``` it appears that the script is not searching the source directory.

My expectation is that if I use settings like this...
```
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '3.1.202'
    config-file: nuget.config
    source-url: https://nuget.pkg.github.com/jeremy-marcus/index.json
  env:
    NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
... then it would be looking for a nuget.config file at ```d:\a\[repo]\[repo]\nuget.config```. Instead it looks for the file in ```d:\a\_temp\nuget.config```.
