### ISSUE TITLE
dotnet build fails for C# 8 on ubuntu-latest, passes on windows/macos-latest

### ISSUE THREAD

**Issue by plioi** [actions/setup-dotnet#99]
### Description

This may appear to be a rehash of  #76, but in my case I am exclusively targeting netcoreapp3.1 solution-wide and am targeting SDK 3.1.201, so C# 8 features ought to be available at compile time. Builds [succeed on windows-latest and macos-latest](https://github.com/fixie/fixie/runs/768647215), but [fail on ubuntu-latest](https://github.com/fixie/fixie/runs/768635196) with mistaken error messages around usages of C# 8's nullable reference types.

Do you have any advice that would help narrow down whether this is a problem with setup-dotnet, the base VM image itself, or something else?

### Details

All csproj target netcoreapp3.1. global.json pins to SDK 3.1.201.

```yml
name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - run: pwsh ./build.ps1
```
